global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nest-api'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['192.168.1.12:3000']
  - job_name: 'nest-api-prod'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['api-cinema-rjku.onrender.com']
